# Generated by Django 5.0.3 on 2024-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('class_name', models.CharField(max_length=50)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
